website/src/Entity/Annonce.php
<?php

namespace App\Entity;

use App\Repository\AnnonceRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=AnnonceRepository::class)
 */
class Annonce
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(
     *      min = 4,
     *      max = 20,
     *      minMessage = "Le nom de l'annonce doit faire au moins 4 caractères",
     *      maxMessage = "Le nom de l'annonce ne doit pas faire plus de 20 caractères"
     * )
     * @Assert\NotBlank(message = "Veuillez entrer un nom pour votre annonce")
    */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(
     *      min = 8,
     *      max = 100,
     *      minMessage = "La description de l'annonce doit faire au moins 8 caractères",
     *      maxMessage = "La description de l'annonce ne doit pas faire plus de 100 caractères"
     * )
     * @Assert\NotBlank(message = "Veuillez entrer une description pour votre annonce")
    */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Positive(message = "La quantité doit être un nombre positif")
     * @Assert\NotBlank(message = "Veuillez entrer une quantité")
    */
    private $quantite;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(
     *      max = 254,
     *      maxMessage = "Le lien de l'image est trop grand"
     * )
    */
    private $image;

    /**
     * @ORM\Column(type="datetime_immutable")
     */
    private $created_at;

    /**
     * @ORM\ManyToOne(targetEntity=Categorie::class, inversedBy="lesAnnonces")
     * @ORM\JoinColumn(nullable=false)
     */
    private $laCategorie;

   
    /**
     * @ORM\ManyToOne(targetEntity=Emplacement::class, inversedBy="lesAnnonces")
     * @ORM\JoinColumn(nullable=false)
     */
    private $emplacement;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="lesAnnonces")
     * @ORM\JoinColumn(nullable=false)
     */
    private $leUser;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getQuantite(): ?string
    {
        return $this->quantite;
    }

    public function setQuantite(string $quantite): self
    {
        $this->quantite = $quantite;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getLaCategorie(): ?Categorie
    {
        return $this->laCategorie;
    }

    public function setLaCategorie(?Categorie $laCategorie): self
    {
        $this->laCategorie = $laCategorie;

        return $this;
    }

  
    public function getEmplacement(): ?Emplacement
    {
        return $this->emplacement;
    }

    public function setEmplacement(?Emplacement $emplacement): self
    {
        $this->emplacement = $emplacement;

        return $this;
    }

    public function getLeUser(): ?User
    {
        return $this->leUser;
    }

    public function setLeUser(?User $leUser): self
    {
        $this->leUser = $leUser;

        return $this;
    }
}

website/src/Controller/MateteController.php
<?php

namespace App\Controller;

use App\Entity\Annonce;
use App\Entity\User;
use App\Repository\AnnonceRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Doctrine\ORM\EntityManagerInterface;
use App\Form\AnnonceType;
use App\Repository\CategorieRepository;
use App\Entity\Categorie;
use App\Entity\Emplacement;
use App\Form\CategorieType;
use App\Repository\EmplacementRepository;
use Doctrine\ORM\EntityManager;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\HttpFoundation\Session\Attribute\AttributeBag;
use Symfony\Component\HttpFoundation\Session\Session;
use Symfony\Component\HttpFoundation\Session\Storage\NativeSessionStorage;
use Symfony\Component\Security\Core\Security;
use Symfony\Component\Validator\Constraints\Length;
use Dompdf\Dompdf;
use Dompdf\Options;

use function PHPUnit\Framework\equalTo;

class MateteController extends AbstractController
{
    private $security;

    public function __construct(Security $security)
    {
       $this->security = $security;
    }

    /**
     * @Route("/", name="carte")
     */
    public function carte(AnnonceRepository $annonce, CategorieRepository $categorie): Response
    {
        return $this->render('matete/carte.html.twig', [
            'annonces' => $annonce->findAll(),
            'categories' => $categorie->findAll()
        ]);
    }

    /**
     * @Route("/lesAnnonces", name="lesAnnonces")
     */
    public function index(Request $request, AnnonceRepository $LesAnnonces, CategorieRepository $lesCategories): Response
    {             
        $page = null;
        $annonces_per_page = 3;
        $annonces = null;

        if($request->query->get('page') != null && intval($request->query->get('page')) > 0){
            $page = intval($request->query->get('page'));
        }else{
            $page = 1;
        }

        $annonces = $LesAnnonces->getPaginatedPosts($page, $annonces_per_page, $request->query->get('recherche'));
        
        //$test_cat = $LesAnnonces->FindByCat('Fruit');
        //dd($test_cat);

        $nb_total_annonces = $LesAnnonces->countAnnonces($request->query->get('recherche'));

        $nb_pages = $nb_total_annonces / $annonces_per_page;
        if ($nb_total_annonces % $annonces_per_page != 0) {
            $nb_pages++;
        }

        $session = new Session(new NativeSessionStorage(), new AttributeBag());
        $session->has('panier') ? $panier = $session->get('panier'): $panier = array();

        return $this->render('matete/index.html.twig', [
            'annonces' => $annonces,
            'panier' => $panier,
            'nb_pages' => $nb_pages,
            'page' => $page,
            'categories' => $lesCategories->findAll(),
            'recherche' => $request->query->get('recherche')
        ]);
    }


     /**
     * @Route("/annonce/{id}", name="annonce_show")
     */
    public function show(AnnonceRepository $annonce, $id): Response
    {   
        $inPanier = false;

        $session = new Session(new NativeSessionStorage(), new AttributeBag());
        $session->has('panier') ? $panier = $session->get('panier'): $panier = array();

        if (array_key_exists($id, $panier))
        {
            $inPanier = true;
        }

        return $this->render('matete/show.html.twig', [
            'annonce' => $annonce->find($id),
            'inPanier' => $inPanier
        ]);
    }

    /**
     * @Route("/nouveau", name="annonce_new")
     */
    public function add(EntityManagerInterface $entityManager, Request $request, CategorieRepository $categorieRepo, EmplacementRepository $emplacementRepo) : Response
    {
        $user = new User();
        //recup user session;
        $user = $this->security->getUser();
        
        $annonce = new Annonce() ;

        $form = $this->createFormBuilder($annonce)
        ->add('nom', TextType::class, ['attr' => ['placeholder' => "Nom", 'class' => 'form-control']])
        ->add('description', TextareaType::class, ['attr' => ['placeholder' => "Description", 'class' => 'form-control mt-3', 'style' => 'resize: none;']])
        ->add('image', FileType::class, ['mapped' => false, 'attr' => ['placeholder' => "Image", 'class' => 'form-control mt-3']])
        ->add('quantite', TextType::class, ['attr' => ['type' => 'number', 'placeholder' => "Quantité (en kg)", 'class' => 'form-control mt-3 quantite']])
        ->add('laCategorie', EntityType::class, ['class' => Categorie::class, 'choices' => $categorieRepo->findAll(), 'attr' => ['class' => 'form-control mt-3']])
        ->add('emplacement', EntityType::class, ['class' => Emplacement::class, 'choices' => $emplacementRepo->findBy(['leUser' => $user->id]), 'attr' => ['class' => 'form-control mt-3']])
        ->getForm();

        $form->handleRequest($request);
        
        //valeur booléenne qui dit si l'utilisateur a des emplacements ou non
        $emplacementEmpty = false;

        if(count($emplacementRepo->findBy(['leUser' => $user->id])) < 1)
        {
            $emplacementEmpty = true;
        }

        if($form->isSubmitted() && $form->isValid()){ //vérif si envoyé et valide
            //récupère l'image uploadée
            $image = $request->files->get('form')['image'];
            //récupère le dossier d'images uploadées
            $uploads_directory = "uploads/public/uploads";
            //créé un nom unique pour l'image
            $filename = md5(uniqid()) . '.' . $image->guessExtension();
            //déplace l'image dans le dossier uploads
            $image->move($uploads_directory, $filename);
            //attribut l'image à l'annonce
            $annonce->setImage($filename);

            //sauvegarde de l’article en bdd
            $time = new \DateTimeImmutable();
            $time->format('H:i:s \O\n d-m-Y');
            $annonce->setCreatedAt($time);
            $annonce->setLeUser($user);
            $entityManager->persist($annonce);
            $entityManager->flush();
            dump($annonce);
            //redirection vers la page de visualisation de l’article
            return $this->redirectToRoute('annonce_show',['id'=>$annonce->getId()]);
        }

        return $this->render('matete/new.html.twig', [
            'emplacementEmpty' => $emplacementEmpty,
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/edit/{id}", name="annonce_edit")
     */
    public function edit(EntityManagerInterface $entityManager, AnnonceRepository $annonce, Request $request, $id, CategorieRepository $categorieRepo, EmplacementRepository $emplacementRepo){

        $user = new User();
        //recup user session;
        $user = $this->security->getUser();

        //protection de l'url
        if(!in_array("ROLE_ADMIN", $user->roles)){
            //récupère les ID des annonces de l'utilisateur connecté
            $Id_annonces_User = array();
            if(count($user->lesAnnonces) == 0){
                throw $this->createNotFoundException(
                    "Vous n'avez pas d'annonce à éditer"
                );
            }

            for($i = 0; $i<count($user->lesAnnonces); $i++){
                array_push($Id_annonces_User, $user->lesAnnonces[$i]->getId());
            }

            //compare l'id entré en paramètre avec les ID des annonces de l'utilisateur connecté
            //cela sert à éviter qu'un utilisateur malveillant puisse éditer (via l'url) une annonce qui ne lui appartient pas
            for($i = 0; $i<count($user->lesAnnonces); $i++){
                if(!in_array($id, $Id_annonces_User)){
                    throw $this->createNotFoundException(
                        "Vous n'avez pas accès à l'annonce ayant pour ID : " . $id
                    );
                }
            }
        }
        
        if (!$annonce) {
            throw $this->createNotFoundException(
                "Il n'y a pas d'annonce ayant l'id : " . $id
            );
        }

        //valeur booléenne qui dit si l'utilisateur a des emplacements ou non
        $emplacementEmpty = false;

        if(count($emplacementRepo->findBy(['leUser' => $user->id])) < 1)
        {
            $emplacementEmpty = true;
        }

        $annonce = $annonce->find($id);
        $form = $this->createFormBuilder($annonce)
        ->add('nom', TextType::class, ['attr' => ['placeholder' => "Nom", 'class' => 'form-control']])
        ->add('description', TextareaType::class, ['attr' => ['placeholder' => "Description", 'class' => 'form-control mt-3', 'style' => 'resize: none;']])
        ->add('image', TextType::class, ['attr' => ['placeholder' => "Image", 'class' => 'form-control mt-3']])
        ->add('quantite', TextType::class, ['attr' => ['type' => 'number', 'placeholder' => "Quantité (en kg)", 'class' => 'form-control mt-3 quantite']])
        ->add('laCategorie', EntityType::class, ['class' => Categorie::class, 'choices' => $categorieRepo->findAll(), 'attr' => ['class' => 'form-control mt-3']]);
        
        //donne tous les emplacements à l'admin et limite ceux des utilisateurs classiques aux leurs
        if(in_array("ROLE_ADMIN", $user->roles)){
                $form = $form->add('emplacement', EntityType::class, ['class' => Emplacement::class, 'choices' => $emplacementRepo->findAll(), 'attr' => ['class' => 'form-control mt-3']]);
        }else{
            $form = $form->add('emplacement', EntityType::class, ['class' => Emplacement::class, 'choices' => $emplacementRepo->findBy(['leUser' => $user->id]), 'attr' => ['class' => 'form-control mt-3']]);
        }

        $form = $form->getForm();

website/templates/matete/edit.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    {% if app.user.suspendu == false %}
        {% if emplacementEmpty == false %}
            {{ form_start(form, {attr: {novalidate: 'novalidate'}}) }}
                <div class='center card' style='width:20%;margin-top:2%;align-items:center'>
                    <div class='card-body'>
                    <h1 class='h3 card-title'>Modifier votre annonce</h1>

                    {{ form_widget(form.nom) }}
                    <div class='text-danger form_error'>{{ form_errors(form.nom) }}</div>
                    
                    {{ form_widget(form.description) }}
                    <div class='text-danger form_error'>{{ form_errors(form.description) }}</div>

                    {{ form_widget(form.image) }}
                    <div class='text-danger form_error'>{{ form_errors(form.image) }}</div>

                    {{ form_widget(form.quantite, { 'type':'number' }) }}
                    <div class='text-danger form_error'>{{ form_errors(form.quantite) }}</div>

                    {{ form_widget(form.laCategorie) }}
                    <div class='text-danger form_error'>{{ form_errors(form.laCategorie) }}</div>

                    {{ form_widget(form.emplacement) }}
                    <div class='text-danger form_error'>{{ form_errors(form.emplacement) }}</div>
                    <button type="submit" class="btn btn-outline-success btn-lg center mt-4 mb-3">Modifier l'annonce</button>
                    <a href="{{ path('annonce_delete', {'id': annonce.id}) }}"  onclick="return confirm('Êtes-vous sûr?')" class='btn btn-outline-danger btn-sm'>Supprimer l'annonce</a><br>
                </div>
                </div>
            {{ form_end(form) }}
        {% else %}
            <h1 class='h3 center mt-1'>Veuillez d'abord ajouter des emplacements à votre profil en cliquant <a href='/showProfil'>ici<a></h1>
        {% endif %}
    {% else %}
    <h1 style="margin-top:5%;"><font color="red"> Vous ne pouvez pas modifier d'annonces </font></h1>
    {% endif %}

<script>
//évite de pouvoir entrer d'autres caractères non numériques
document.querySelector(".quantite").addEventListener("keypress", function (evt) {
    if (evt.which != 8 && evt.which != 0 && evt.which < 48 || evt.which > 57)
    {
        evt.preventDefault();
    }
});
</script>

{% endblock %}

website/templates/matete/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<h1 class='center mt-2'>Les Annonces</h1>
<select class='form-control mb-3' style="width:10%;position:relative;left:45%" onchange="changeCategorie(this)">
<option value='Tout'>Toutes catégories</option>
{% for categorie in categories %}
<option value='{{categorie.nom}}'>{{categorie.nom}}</option>
{% endfor %}
</select>
<div class='d-flex justify-content-center'>
    <input id='recherche' value='{{ recherche }}' type='text' class='form-control w-25 mb-3 mx-2' placeholder='Rechercher'>
    <button class='btn btn-primary h-25' onclick="recherche();">Rechercher</button>
</div>
{% if annonces|length < 1 %}
    <h4 class='center mt-2'>Il n'y a pas d'annonces pour le moment.</h4>
{% else %}
    <div class="container">
    <div class="row">
    {% for annonce in annonces %}
        <div class="col-md-4 mt-3 Tout {{annonce.laCategorie.nom}}" id='{{annonce.id}}'>
        <div class="card mb-3 h-100" id='{{annonce.id}}'>
            <div class="card-body">
                <h5 class="card-title"><strong>{{annonce.nom}}</strong></h5>
                <h6 class="card-subtitle text-muted">de {{annonce.leUser.username}}</h6>
                {% if app.user and annonce in app.user.lesAnnonces %}
                    <h5 class='badge bg-info' style='position:absolute; color:white; left:5.5%; top:13%'>Votre annonce</h5>
                {% elseif annonce.id in panier|keys %}
                    <!--badge panier-->
                    <h5 class='badge bg-success' style='position:absolute; color:white; left:5.5%; top:13%'><a class='simple-link' href="{{ path('panier_delete', {'id': annonce.id, 'from': 'lesAnnonces'}) }}"><i class='uil uil-times times' style='font-size:13px' onmouseover="hover(this);" onmouseleave="noHover(this);"></i></a> <a href='/panier' class='simple-link'>Dans votre panier</a></h5>
                {% endif %}
            </div>
            <div style='width:95%; height:250px ;margin: 0 auto;'>
                <img class='center w-100 text-center' src="{{ '/uploads/public/uploads/' ~ annonce.image }}" alt="Image de l'annonce" style='border-radius:6px;height:250px;object-fit: cover;'>
            </div>
            <div class="card-body">
                <p class="card-text">{{annonce.description}}</p>
                <hr class="mt-2">
                <a href="{{ path('annonce_show', {'id': annonce.id}) }}" class='btn btn-outline-dark p-2' style='margin-top:3.5%'>Voir plus</a>
                {% if app.user %}
                    {% if annonce.id not in panier|keys and annonce not in app.user.lesAnnonces %}
                        <a href="{{ path('ajouter_panier', {'id': annonce.id, 'from': 'lesAnnonces'}) }}" class='btn btn-outline-success' style='margin-top:3.5%'><i class='uil uil-shopping-cart'></i>Ajouter au panier</a>
                    {% endif %}
                    {% if annonce in app.user.lesAnnonces %}
                        <a href="{{ path('annonce_edit', {'id': annonce.id}) }}" class='btn btn-outline-info p-2' style='margin-top:3.5%'>Modifier</a>
                    {% endif %}
                {% else %}
                    {% if annonce.id not in panier|keys %}
                        <a href="{{ path('ajouter_panier', {'id': annonce.id, 'from': 'lesAnnonces'}) }}" class='btn btn-outline-success' style='margin-top:3.5%'><i class='uil uil-shopping-cart'></i>Ajouter au panier</a>
                    {% endif %}
                {% endif %}
            </div>
             <div class='card-footer'>
                <small class="text-muted">{{annonce.createdAt|date('d-m-Y')}}</small>
            </div>
            </div>
        </div>
    {% endfor %}
    </div>
    </div>
{% endif %}

{% if annonces|length > 0 %}
<div class='d-flex mt-5 mb-5' style='margin: 0px auto;text-align:center; justify-content: center;'>

{% if (page - 1) > 0 %}
    <a class='btn btn-outline-dark rounded-0 mx-1' href="/lesAnnonces?page={{ page - 1 }}&recherche={{ recherche }}"><i class='uil uil-arrow-left'></i>Précédent</a>
{% else %}
    <a class='btn btn-outline-dark rounded-0 mx-1 disabled'><i class='uil uil-arrow-left'></i>Précédent</a>
{% endif %}

{% if nb_pages > 2 %}
{% for i in 0..(nb_pages - 1) %}
        {% if page - 1 == i %}
            <a class='btn btn-outline-dark rounded-0 mx-1 active' href="/lesAnnonces?page={{i + 1}}&recherche={{ recherche }}">{{ i + 1 }}</a>
        {% else %}
            <a class='btn btn-outline-dark rounded-0 mx-1' href="/lesAnnonces?page={{i + 1}}&recherche={{ recherche }}">{{ i + 1 }}</a>
        {% endif %}
 {% endfor %}
{% endif %}

 {% if (page + 1) < nb_pages %}
    <a class='btn btn-outline-dark rounded-0 mx-1' href='/lesAnnonces?page={{ page + 1 }}&recherche={{ recherche }}'><i class='uil uil-arrow-right'></i>Suivant</a>
{% else %}
    <a class='btn btn-outline-dark rounded-0 mx-1 disabled'><i class='uil uil-arrow-right'></i>Suivant</a>
{% endif %}
</div>
{% endif %}

<script>
function changeCategorie(selectedOption){
    var value = selectedOption.value;
    
    //récupère toutes les cards
    var allCards = document.getElementsByClassName("Tout");
    //on fait d'abord disparaitre toutes les cards sans exception
    for(var i = 0; i < allCards.length; i++){
        allCards[i].style.display = "none";
    }

    //récupère les cards ayant pour categorie la categorie selectionnée avec le select
    var relatedCards = document.getElementsByClassName(value);
    //re-affiche les annonces ayant la categorie choisie dans le select
    for(var i = 0; i < relatedCards.length; i++){
        relatedCards[i].style.display = "block";
    }
}

function hover(element){
    element.className = "uil uil-times-circle"
}

function noHover(element){
    element.className = "uil uil-times"
}

function recherche(){
    var recherche = document.getElementById("recherche").value;
    var url = "/lesAnnonces?recherche=" + recherche;
    window.location.href = url;
}
</script>
{% endblock %}

website/templates/matete/new.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    {% if app.user.suspendu == false and app.user.enabled == true%}
        {% if emplacementEmpty == false %}
            {{ form_start(form, {attr: {novalidate: 'novalidate'}}) }}
                <div class='center card' style='width:20%;margin-top:2%;align-items:center'>
                    <div class='card-body'>
                    <h1 class='h3 card-title'>Créer une annonce</h1>

                    {{ form_widget(form.nom) }}
                    <div class='text-danger form_error'>{{ form_errors(form.nom) }}</div>
                    
                    {{ form_widget(form.description) }}
                    <div class='text-danger form_error'>{{ form_errors(form.description) }}</div>

                    {{ form_widget(form.image) }}
                    <div class='text-danger form_error'>{{ form_errors(form.image) }}</div>

                    {{ form_widget(form.quantite, { 'type':'number' }) }}
                    <div class='text-danger form_error'>{{ form_errors(form.quantite) }}</div>

                    {{ form_widget(form.laCategorie) }}
                    <div class='text-danger form_error'>{{ form_errors(form.laCategorie) }}</div>

                    {{ form_widget(form.emplacement) }}
                    <div class='text-danger form_error'>{{ form_errors(form.emplacement) }}</div>
                    <button type="submit" class="btn btn-outline-success btn-lg center mt-4 mb-3">Poster l'annonce</button>
                </div>
                </div>
            {{ form_end(form) }}
        {% else %}
            <h1 class='h3 center mt-2 mx-2'>Veuillez d'abord ajouter des emplacements à votre profil en cliquant <a href='/showProfil'>ici<a>.</h1>
        {% endif %}
    {% else %}
    <h3 class='mt-1 mx-2 text-danger'>Vous ne pouvez pas créer d'annonces</h3>
    {% endif %}

<script>
//évite de pouvoir entrer d'autres caractères non numériques
document.querySelector(".quantite").addEventListener("keypress", function (evt) {
    if (evt.which != 8 && evt.which != 0 && evt.which < 48 || evt.which > 57)
    {
        evt.preventDefault();
    }
});
</script>

{% endblock %}

website/templates/matete/panier.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<div class='center'>
    <h1 class='mt-2'>Votre panier</h1>
    {% if annonces|length < 1 %}
        <h4 class='center'>Vous n'avez pas encore d'annonces dans votre panier. Cliquez <a href='{{ path('lesAnnonces') }}' class='text-primary'>ici</a> pour voir les annonces.</h4>
    {% else %}
    <a href="/pdf" class="btn btn-outline-info btn-lg mt-2 mb-2"><i class='uil uil-print'></i> Imprimer le panier</a>
    <div class='container'>
    <div class='row'>
    {% for annonce in annonces %}
        <div class="col-md-4 mt-3 Tout {{annonce.laCategorie.nom}}" id='{{annonce.id}}'>
         <div class="card mb-3 h-100" id='{{annonce.id}}'>
            <div class="card-body">
                <h5 class="card-title"><strong>{{annonce.nom}}</strong></h5>
                <h6 class="card-subtitle text-muted">de {{annonce.leUser.username}}</h6>
            </div>
            <div style='width:95%; height:300px ;margin: 0 auto;'>
                <img class='center w-100 text-center' src="{{ '/uploads/public/uploads/' ~ annonce.image }}" alt="Image de l'annonce" style='border-radius:6px;height:250px;object-fit: cover;'>
            </div>
            <div class="card-body">
                <p class="card-text">{{annonce.description}}</p>
                <hr class="mt-2">
                <a href="{{ path('annonce_show', {'id': annonce.id}) }}" class='btn btn-outline-dark p-2' style='margin-top:3.5%'>Voir plus</a>
                <a href="{{ path('panier_delete', {'id': annonce.id, 'from': 'panier'}) }}" class='btn btn-outline-warning p-2' style='margin-top:3.5%'>Retirer du panier</a><br>
            </div>
             <div class='card-footer'>
                <small class="text-muted">{{annonce.createdAt|date('d-m-Y')}}</small>
            </div>
            </div>
        </div>
    {% endfor %}
    </div>
    </div>
    {% endif %}
</div>
{% endblock %}

website/templates/matete/pdf.html.twig
{% block body %}
<center>
    <h1><ins>Votre panier</ins></h1><br>
    {% for annonce in annonces %}
        <h3>Nom de l'Annonce :
            {{annonce.nom}}</h3>
        <h5>Description :
            {{annonce.description}}</h5>
        <h5> Contenu de l'annonce : {{annonce.quantite}} {{annonce.laCategorie}}s</h5>
        <h5>Emplacement :
            {{annonce.emplacement}}</h5>
        <h5>Contactez {{annonce.leUser}} :
            <br>numéro : {{annonce.leUser.numTel}}
            <br>email : {{annonce.leUser.email}}</h5>
        <hr>
    {% endfor %}
<center>
{% endblock %}